import React, { PropsWithChildren } from "react";
import { BankOutlined } from "@ant-design/icons";
import { Breadcrumb, Layout as AntdLayout, Menu, theme } from "antd";
const { Header, Content, Sider } = AntdLayout;
import Head from "next/head";

import styles from "./index.module.css";

import MainMenu from "@/components/Layout/MainMenu/index";
import HeaderHover from "@/components/Layout/HeaderHover/index";

const Layout: React.FC<PropsWithChildren> = ({children}) => {
  const {
    token: { colorBgContainer },
  } = theme.useToken();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <AntdLayout>
          <Header
            style={{ display: "flex", alignItems: "center" }}
            className={styles.header}
          >
            <div className={styles.demo_logo}>
              <BankOutlined className={styles.header_logo} />
              Book Management System
            </div>
            <span className={styles.header_hover}>
              <HeaderHover />
            </span>
          </Header>
          <AntdLayout className={styles.main_section}>
            <Sider className={styles.main_sider} style={{ background: colorBgContainer }}>
              <MainMenu />
            </Sider>
            <AntdLayout className={styles.main_section_content}>
              <Content className={styles.main_content}>
                {children}
              </Content>
            </AntdLayout>
          </AntdLayout>
        </AntdLayout>
      </main>
    </>
  );
};

export default Layout;
